<?php

return [
    'budgets' => [
        '0 - 1,000,000',
        '1,000,000 - 2,000,000',
        '2,000,000 - 3,000,000',
        '3,000,000 - 4,000,000',
        '4,000,000 - 5,000,000',
        '> 5,000,000'
    ],
    
    'materials' => [
        '3D Render / CGI',
        'Acrylic on Canvas',
        'Acrylic on Panel',
        'Aluminum',
        'Animation',
        'Aquatint',
        'Archival Pigment Print',
        'Bronze',
        'C-Print',
        'Ceramic',
        'Charcoal on Paper',
        'Collage',
        'Digital Artwork',
        'Digital Print',
        'Embroidery',
        'Encaustic',
        'Engraving',
        'Etching',
        'Fabric + Mixed Media',
        'Fiber Art',
        'Fiberglass',
        'Found Objects',
        'Giclée Print',
        'Glass',
        'Gold Leaf on Canvas',
        'Gold Leaf on Paper',
        'Graphite on Paper',
        'Gouache on Paper',
        'Handmade Paper',
        'Ink on Canvas',
        'Ink on Paper',
        'Inkjet Print',
        'Interactive Media',
        'Light Installation',
        'Linocut',
        'Lithograph',
        'Marble',
        'Marker on Paper',
        'Mixed Media Calligraphy',
        'Mixed Media Installation',
        'Mixed Media on Canvas',
        'Mixed Media on Panel',
        'Mixed Media on Paper',
        'Mixed Media Sculpture',
        'Monotype / Monoprint',
        'NFT (Digital Asset)',
        'Oil on Canvas',
        'Oil on Panel',
        'Parchment',
        'Pastel on Paper',
        'Pencil on Paper',
        'Plaster',
        'Quilting',
        'Resin',
        'Screenprint (Silkscreen)',
        'Silver Gelatin Print',
        'Site-Specific Installation',
        'Sound Installation',
        'Spray Paint',
        'Stainless Steel',
        'Steel',
        'Stone',
        'Tempera on Board',
        'Textile',
        'Tapestry',
        'Video Art',
        'Video Installation',
        'Watercolor on Paper',
        'Weaving',
        'Wood',
        'Woodcut',
        'Other',
    ],

    'medium_type' => [
        'Calligraphy',
        'Digital Art',
        'Drawing / Works on Paper',
        'Installation',
        'Painting',
        'Photography',
        'Prints',
        'Sculpture',
        'Textile / Fabric / Fiber Art',
        'Other',
    ],


    'exhibition_types' => [
    	'Biennales',
    	'Collective',
    	'Fairs',
        'Solo',    
    ],
    'artwork_categories' => [
        [
            'title' => 'Abstract',
            'image1' => 'Abstract-top.webp',
            'image2' => 'Abstract-back.webp',
        ],
        [
            'title' => 'Arabic Calligraphy',
            'image1' => 'Arabic-Calligraphy-top.webp',
            'image2' => 'Arabic-Calligraphy-bottom.webp',
        ],
        [
            'title' => 'Modern',
            'image1' => 'Modern-top.webp',
            'image2' => 'Modern-back.webp',
        ],
        [
            'title' => 'Contemporary',
            'image1' => 'Abstract-top.webp',
            'image2' => 'Abstract-back.webp',
        ],
        [
            'title' => 'Sculpture',
            'image1' => 'Sculpture-top.webp',
            'image2' => 'Sculpture-back.webp',
        ],
        [
            'title' => 'Photography',
            'image1' => 'Photography-top.webp',
            'image2' => 'Photography-back.webp',  
        ],
    ],
];